#!/bin/bash
# info @ https://wiki.archlinux.org/title/xmodmap
# info on keycodes: https://gist.github.com/rickyzhang82/8581a762c9f9fc6ddb8390872552c250


xmodmap -e "clear Mod1"
xmodmap -e "clear Mod2"
xmodmap -e "clear Mod3"
xmodmap -e "clear Mod4"
xmodmap -e "clear Mod5"

xmodmap -e "clear Control"
xmodmap -e "clear Shift"
xmodmap -e "clear Lock"

xmodmap -e "clear Alt"
xmodmap -e "clear Enter"




exit


# disable everything except keys_enable
# disables mouse clicks...
keys_enable=(65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 86 87 88 89 90 118 119 120 121 122)

for i in {1..255}
do
  if [[ ! "${keys_enable[*]}" =~ "${i}" ]]; then
      xmodmap -e  "keycode $i=0"
  fi
done

